---
- name: Prepare environment
  ansible.builtin.import_playbook: setup.yml
  tags: [setup]

- name: Deploy
  hosts: webservers

  tasks:
    - name: Run redmine
      community.docker.docker_container:
        name: redmine
        image: 'redmine:{{ version | default("5.0.2-alpine") }}'
        restart_policy: always
        state: started
        ports:
          - 80:3000
        env_file: /.env
