---
- hosts: webservers
  gather_facts: yes
  vars:
    ip4: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"

  pre_tasks:
    - name: create config for http_check agent
      tags: [datadog, datadog-conf]
      template:
        src: templates/http_check.d/conf.yml.j2
        dest: /etc/datadog-agent/conf.d/http_check.d/conf.yaml
        owner: dd-agent

  roles:
    - role: geerlingguy.docker
    - role: datadog.datadog
      tags: datadog
      become: yes
      vars:
        datadog_api_key: '{{datadog_key}}'
        datadog_site: 'us5.datadoghq.com'
        datadog_checks:
          process:
            init_config:
            instances:
              - name: http_check
                exact_match: False
                search_string: ['http_check', 'http_check.d']
                url: http://0.0.0.0:80
                method: get
                http_response_status_code: 200

  tasks:
    - name: apt update cache
      apt:
        update_cache: yes

    - name: install pip
      apt:
        name: python3-pip

    - name: setup env vars
      tags: env
      template:
        src: templates/.env.j2
        dest: /.env
