---
- name: Setup
  hosts: webservers
  gather_facts: true

  roles:
    - role: geerlingguy.docker
    - role: datadog.datadog
      tags: datadog
      become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install pip
      ansible.builtin.apt:
        name: python3-pip

    - name: Create .env file
      ansible.builtin.template:
        src: .env.j2
        dest: /.env
        mode: '0644'
