datadog_api_key: "{{ datadog_key }}"
datadog_site: "us5.datadoghq.com"
datadog_checks:
  process:
    init_config:
    instances:
      - name: http_check
        exact_match: false
        search_string: ["http_check", "http_check.d"]
        url: "http://0.0.0.0:{{ app_port }}"
        method: get
        http_response_status_code: 200
